---
title: "Metadata exemplar"
resources: 
  fire_inspections.html
  fire_inspections.json
---

We provide metadata for open data sets to help people discover, use, and interpret the data sets we publish. There are four types of metadata records for open data sets: Catalog records, Data set records, Distribution records, and Data Dictionaries.

- **Catalog** records group together data set records and contain a high level technical description of the collection of data sets as a whole. Through ArcGIS Online (AGO), for example, there is a catalog record with an entry for each and every data set available through the Open Data Portal.  
- **Data set** records are used to describe each data set as a whole. They contain information such as title, keywords, a narrative description, and the spatial and temporal scope of data included in the data set. Data set records are nested in catalogs.
- **Distribution** records describe files and APIs through which the public can access and obtain copies of data sets. Data distribution records are nested inside data set records.
- **Data dictionaries** describe individual data fields (i.e., columns or variables) that comprise a data set. Data dictionaries are linked to data set records.

Typically, most of the metadata in catalog and distribution records are created programmatically by DSA staff and the systems we license or implement. Metadata in data set records and data dictionaries incorporate information from a broader set of sources. These records are individually curated and include departmental knowledge shared by data stewards and other departmental experts.    



## Creating metadata
Metadata is created through three primary processes:

1. Data stewards or other departmental experts record data set and data dictionary metadata using an [Excel](https://cidetroitmius.sharepoint.com/:x:/r/sites/M365-DoIT-DSA-BusinessTruth/Shared%20Documents/Business%20Truth/Working_files/metadata/DFD_Fire_Inspections_ODP_data_dictionary.xlsx?d=w28b8aa9dea904c9180d1e9b94b1fdf1c&csf=1&web=1&e=KIdmrn) or web-based template (under development).
2. Internal scripts are used to query and summarize data values that are recorded in metadata records.
3. Metadata is assigned through AGO site-wide settings and ingestion processes.


## Reviewing data

Data profiles provide a view into the structure and content of ODP data sets, at selected points in the ingest-transformation-publication workflow. For [this example](https://lsheble.github.io/odp_meta_preview/exemplar/inspect_df_trial_fire_inspections.html), the Fire Inspections data set was downloaded from AGO and imported for examination. 

## HTML Preview and Google Rich Results Test

An [HTML display mockup](fire_inspections.html) with embedded schema.org "dataset" and "distribution" metadata presents an early glimpse of the potential for a static HTML file to present metadata. The schema.org metadata schema was selected because Google Search, including Google Data Search, relies on structured data embedded in websites that adhere to the schema.org vocabulary. This vocabulary, like the DCAT-US v1.1 vocabulary, is based on the W3C Data Catalog Vocabulary (DCAT) standard.

[Results from the Google "Rich Results Test" for our HTML display mockup](https://search.google.com/test/rich-results/result?id=hr9bNv8lqijPG6kwVDElTw) show that in addition to the "Dataset" and "Distribution" metadata, the structured format of variable-level metadata (column or variable name and description) is also identified. 


## Metadata on AGO

Through the ArcGIS Online Open Data Portal:

- Some metadata will be displayed on a data set's ['about' page](https://data.detroitmi.gov/datasets/detroitmi::fire-inspections/about)
- Full metadata will be displayed from the ['View All Metadata' selection](https://www.arcgis.com/sharing/rest/content/items/0bac58a27da04e4a95910cb6488b7fe9/info/metadata/metadata.xml?format=default&output=html) 


## DCAT-US v 1.1 schema from AGO

## Data dictionary formats 


