project:
  type: website
  output-dir: docs
  resources: 
    - "*.html"

website:
  page-navigation: true
  title: "ODP Metadata Docs Preview"
  repo-url: "https://github.com/lsheble/odp_meta_preview"
  repo-actions: [edit, issue]
  
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - section: exemplar/index.qmd
        contents:
          - exemplar/inspect_df_trial_fire_inspections.qmd
          - exemplar/fire_inspections.html
      - section: metadata_flow/index.qmd
        contents:
          - metadata_flow/new_from_cod_to_odp.qmd
      - href: data_dot_gov.qmd
        text: Data discovery
      - about.qmd


format:
  html:
    theme: default
    css: styles.css
    toc: true



