project:
  type: website
  resources: 
    - "fire_inspections.html"
  output-dir: docs

website:
  title: "odp_meta_preview"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - inspect_df_trial_fire_inspections.Rmd
      - fire_inspections.html
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



