---
title: "Preparing ODP data for Data.gov"
format: 
  html:
    code-fold: true
---


The Data.gov website serves as a centralized data catalog the public can use to discover public data. The primary focus is federal data though state and local governments and NGOs are invited to have catalog, data set, and data distribution metadata included in the catalog. To do so, organizations can sign up to have metadata harvested through a DCAT-US 1.1 compliant API. [DCAT-US schema version 1.1](https://resources.data.gov/resources/dcat-us/) metadata requirements are published on resources.data.gov. The json-ld schema for DCAT 1.1 is available at the URL https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld.  


Through ArcGIS Online (AGO), [the ODP has an JSON endpoint](https://data.detroitmi.gov//api/feed/dcat-us/1.1.json) that meets Data.gov format requirements. AGO therefore provides an approach to having ODP data included in the Data.gov catalog fairly easily (see figure). Additions, updates, and deletions to the Data.gov catalog occur through the harvest source rather than within Data.gov directly. Data.gov synchronizes changes daily through a harvest job.


::: {fig-ago-records-datagov}

```{mermaid}
%%| Label: ago-records-datagov
flowchart TB

%% classDef
classDef classBlue color: #55a5f6,fill:#f1f1f1,stroke-width:2px,stroke:#55a5f6,font-weight:bold
classDef classRed color: #af0659,fill:#e0e5eb,stroke-width:2px,stroke:#af0659
classDef classMd color: #c96195,fill:#f1f1f1,stroke-width:2px,stroke:#c96195,font-weight:bold
classDef classDB color: #0980b0,fill:#f1f1f1,stroke-width:2px,stroke:#0980b0
classDef classFile color:#17559e,fill:#f1f1f1,stroke:#55a5f6
classDef classFile2 color:#17559e,fill:#f1f1f1,stroke:#55a5f6
classDef classBlOutline color:#0980b0,fill:#ffffff,stroke:#0980b0
classDef classCityGreen color:#004445,stroke-width:2px,fill:#F2F2F2,stroke:#004445
classDef classSpiritGreen color:279989,stroke-width:2px,fill:#F2F2F2,stroke:#279989
classDef classAccentYellow color:#18252A,stroke-width:2px,fill:#F2F2F2,stroke:#feb70d

  subgraph Catalog_Record
    direction LR
    d1[[Dataset <br> record 1]]
    d2[[Dataset <br> record 2]]
    d3[[Dataset <br> record n]]
  end  
  A[(AGO <br> geodatabase)] -. exposes DCAT-US v1.1 <br> metadata .-> Catalog_Record -. harvested by <br> Data.gov .-> C[(Data.gov <br> catalog)]

%%Style

class A,d1,d2,d3,Catalog_Record classSpiritGreen
class C classAccentYellow
```

DCAT-US v 1.1 compliant ODP metadata can be harvested from AGO to be included in data.gov 

::: 

## Adding local government data to Data.gov


The article ["How to get your Open Data on Data.gov"](https://resources.data.gov/resources/data-gov-open-data-howto/) provides instructions for having Open Data harvested by Data.gov and includes details specific to non-federal data publishers.

At a local level, a number of recommended policy, quality assurance, and related steps have been identified through review of our metadata and other local data resources. An overview of recommendations developed to date follow. Progress on the recommendations is being tracked on Github.

### Steps to ensure metadata meets local and Data.gov publishing criteria [DRAFT]

1. Develop a terms of use / data policy for data sets shared through the Detroit Open Data Portal. To be in compliance with data.gov requirements, this policy should be accessible via a stable URL. 
2. Identify a single point of contact to which/whom data.gov staff can refer questions about Detroit data sets. This point of contact should be able to triage questions about Detroit data.
3. Ensure every data set meets the minimum metadata requirements. To help with this, metadata can be validated using a .json catalog endpoint or by file upload at https://labs.data.gov/dashboard/validate. Results from an initial validation of our catalog were analyzed and issues to be remedied are available on GitHub. Moving forward, validation checks should be repeated periodically or continuously as developing metadata procedures are instituted. To review current validation results, see real-time results [in the browser](https://dashboard.data.gov/validate?schema=non-federal-v1.1&output=browser&datajson_url=https%3A%2F%2Fdata.detroitmi.gov%2F%2Fapi%2Ffeed%2Fdcat-us%2F1.1.json&qa=true) or the [JSON formatted file](https://dashboard.data.gov/validate?schema=non-federal-v1.1&output=json&datajson_url=https%3A%2F%2Fdata.detroitmi.gov%2F%2Fapi%2Ffeed%2Fdcat-us%2F1.1.json&qa=true). 
4. Steps to help ensure metadata associated with newly published data meets the Data.gov standard should be integrated into data publication workflows and instructions.
5. In some cases, element-level metadata of the type that would be included in a data dictionary has been directly entered in the data set description fields on AGO. As metadata processes and standards are formalized, it may be helpful to review metadata displays and available alternatives. In collaboration with data stewards and other stakeholders, benefits and limitations of retrospectively reformatting metadata could be reviewed. 
6. Evaluate the interpretability of local metadata in broader contexts such as Data.gov context.
7. Review the catalog of data sets available via our JSON endpoint and determine if all are appropriate to share via Data.gov. If any data set is not suitable to share through the catalog, methods to exclude such data sets, and how this would impact data published through the ODP would need to be identified and taken into account. 

::: {.callout-tip}
[Github issue #1168](https://github.com/CityOfDetroit/data-engineering/issues/1168) and related sub-issues are being used to track progress on recommendations.
:::


## Data.gov sign-up and registration requirements

Local governments and others are invited to [sign up](https://data.gov/local/add/) to have local data federated to Data.gov. When doing so, the following information is requested:

- Name of the government entity
- Name and email address of individual requesting to have data catalog included
- Data Catalog Data.json URL
- Data Catalog Terms of Use URL
- Additionally, details about data included in the catalog from other sources such as the Federal Government, State Government, or a non-profit is requested.



